language: java

jdk:
- openjdk8

sudo: true
dist: trusty

cache:
  directories:
  - $HOME/.m2
  - kura/target-definition
  - target-platform/p2-repo-common/target
  - target-platform/p2-repo-equinox_3.12.50/target
  - target-platform/p2-repo-test-deps/target

before_script:
  - echo ==== Setting up toolchain.xml ====
  - ls /usr/lib/jvm
  - cp kura/setups/toolchains/toolchains-travis.xml ~/.m2/toolchains.xml
  - echo ==== Setting up Maven 3.3 for Travis ====
  - wget -O maven.tar.gz http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - mkdir maven
  - cd maven ; tar --strip-components 1 -xzf ../maven.tar.gz ; cd ..
  - chmod a+x maven/bin/mvn
  - export M2_HOME=$PWD/maven
  - export PATH=${M2_HOME}/maven/bin:${PATH}
  - hash -r
  - sudo useradd kura

addons:
  apt:
    packages:
      - dos2unix
      - openjdk-8-jdk

jobs:
  include:
    - stage: Main-build
      script:
        - rm -rf $HOME/.m2/repository/org/eclipse
        - rm -rf kura/target-definition/{common,equinox*,test-deps}
        - $M2_HOME/bin/mvn -B -f target-platform/pom.xml clean install
        - $M2_HOME/bin/mvn -B -f kura/pom.xml clean install -Dtycho.localArtifacts=ignore -DskipTests
    - stage: distrib-examples-tests
      script: $M2_HOME/bin/mvn -f kura/distrib/pom.xml clean install
      name: Distribution
    - script: $M2_HOME/bin/mvn -f kura/examples/pom.xml clean install
      name: Examples
    - script: $M2_HOME/bin/mvn -f kura/test/pom.xml clean install
      name: Tests

after_script:
  - sudo userdel kura
