language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gLEymzqzdMsTS4rQxwWGMDNLeU8S09lhvENIgyPF/cZ6wjnt92W4iRLrEEmZw5JYttQM+czekQ+R7RVFuwxL8Ut9BllnYf3sSuU4KUi3oG+N51z9XRAaRRjtHiZvpn0BehrqcGWKviKKh52KE20SMCMpGrmWnHIHKWI3ZKQuvfU="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "eclipse/kura"
      description: "Eclipse Kura"
    notification_email: david.woodard@eurotech.com
    build_command_prepend: "rm -rf $HOME/.m2/repository/org/eclipse && rm -rf kura/target-definition/{common,equinox*,test-deps}"
    build_command: "mvn -B -f target-platform/pom.xml clean install && mvn -B -f kura/pom.xml clean install -DskipTests"
    branch_pattern: coverity_scan

